version: "3.4"

services:

  file-exporter:
    build:
      context: .
    image: asset-repository-file-exporter:local
    environment:
      - ASSET_REPOSITORY_URL=http://caddy:8080
    volumes:
      - ./src:/app
      - ./examples:/app/requests
    command: [ '-m', 'daemon']

  # backend PHP for tests
  php:
    image: ghcr.io/beerfranz/asset-repository-php:0.0.2-4
    depends_on:
      - database
    volumes:
      - php_socket:/var/run/php
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-!ChangeMe!}@database:5432/${POSTGRES_DB:-app}?serverVersion=${POSTGRES_VERSION:-14}
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}
      TRUSTED_HOSTS: ^${SERVER_NAME:-example\.com|localhost}|caddy$$
      MERCURE_URL: ${CADDY_MERCURE_URL:-http://caddy/.well-known/mercure}
      MERCURE_PUBLIC_URL: https://${SERVER_NAME:-localhost}/.well-known/mercure
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      AUTH_HEADER_ROLES: x-token-user-roles
      AUTH_HEADER_EMAIL: x-token-user-email

  # backend web server for tests
  caddy:
    image: ghcr.io/beerfranz/asset-repository-caddy:0.0.2-4
    depends_on:
      - php
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}, caddy:80, http://caddy:8080
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
    volumes:
      - php_socket:/var/run/php
      - caddy_data:/data
      - caddy_config:/config
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp

  # Database for tests
  database:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-app}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-!ChangeMe!}
      - POSTGRES_USER=${POSTGRES_USER:-app}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  php_socket:
  caddy_data:
  caddy_config:
  db_data:
